name: Create Tag

on:
  push:
    paths:
      - VERSION
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        strategy: regex
        root: "VERSION"
        regex_pattern: "^(\\d+\\.\\d+\\.\\d+)$"
        tag_prefix: "v"
        tag_message: "Tagged by Autotag Github Action."
